<option>--</option>
<option>AA</option>
<option>A</option>
<option>AB</option>
<option>B</option>
<option>BC</option>
<option>C</option>
<option>CD</option>
<option>D</option>
<option>F</option>
<option>SICK</option>
<option>DEAD</option>
</select>
