1	National Diploma in Business Administration and Management	0					
2	ND BUSINESS ADMINISTRATION AND MANAGEMENT	0	BAM	COLLEGE OF ADMINISTRATIVE AND BUSINESS STUDIES	CABS	SCHOOL OF BUSINESS STUDIES	SBS
3	HND BUSINESS ADMINISTRATION AND MANAGEMENT	0	BAM	COLLEGE OF ADMINISTRATIVE AND BUSINESS STUDIES	CABS	SCHOOL OF BUSINESS STUDIES	SBS
4	PRE- HND BUSINESS ADMINISTRATION AND MANAGEMENT	0	BAM	COLLEGE OF ADMINISTRATIVE AND BUSINESS STUDIES	CABS	SCHOOL OF BUSINESS STUDIES	SBS
